# SPDX-License-Identifier: MIT

option(KS_SERIALIZATION_BUILD_TEST "Build ${PROJECT_NAME} unittest" ${PROJECT_IS_TOP_LEVEL})
option(KS_SERIALIZATION_INSTALL "Install ${PROJECT_NAME}" ${PROJECT_IS_TOP_LEVEL})
option(KS_SERIALIZATION_BUILD_BENCHMARK "Build ${PROJECT_NAME} benchmarks" ${PROJECT_IS_TOP_LEVEL})
