name: OSX
on: push
jobs:
  BuildAndTest:
    runs-on: macos-14
    steps:
      - name: Checkoout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11.5

      - name: Build and test
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'default'
